[package]
name = "rmpd_adschedule"
version = "0.2.0"
authors = ["Oleg Antonyan <oleg.b.antonyan@gmail.com>"]

[dependencies]
time = "*"
libc = "*"
rustc-serialize = "*"
itertools = "*"

[lib]
crate-type = ["cdylib"]
